### ISSUE TITLE
Result pages background dots sticking around

### ISSUE THREAD

**Issue by enorar** [lsecities/urbangovernance-wp-theme#5]
It seems like when we select different cities on the results page, they appear in light grey in the background maps and the grey dots stick around even when we select a new city (we should only see one city in grey on the background map, the one that we have chosen to follow). It would be great if we could correct that

**Comment by hotzeplotz** [comment]
this one is for Roxana - it shouldn't have a huge impact in the meanwhile. i'll add a label so that we keep track of issues to forward to her.

**Comment by enorar** [comment]
OK thanks a lot!

**Comment by hotzeplotz** [comment]
This was fixed by Roxana in 004063601b4ad0f7f5cee5bdcd8c4e302c0c46a9. Thanks!
