### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by enorar** [lsecities/urbangovernance-wp-theme#6]
We would need to have a side bar on the About and Survey Form pages.

**Comment by hotzeplotz** [comment]
ok - this feature is ready too - any page whose 'Sidebar' field has any content (this field should be at the very bottom of the page content entry screen) will display this sidebar content in a sidebar, shrinking the main page content to 3/4 of the screen width.

**Comment by hotzeplotz** [comment]
forgot to mention - at the moment this only works if a page is only available in a single language. for multilingual support, things are a bit more complicated and i need to do more checks.

**Comment by hotzeplotz** [comment]
after a final update and testing, this feature works across languages.
