### ISSUE TITLE
Changing authorship in the case study section

### ISSUE THREAD

**Issue by enorar** [lsecities/urbangovernance-wp-theme#7]
We would need to be able to change authorship in the case study section including new authors (and their contact/email address) - it seems like currently, we are only allowed to update the author name with the names of the people who have access to the content management platform. But we will have external contributors (and we will then be in charge of uploading the case study on the website)

**Comment by hotzeplotz** [comment]
having looked at the code, this can be done by manually adding author(s) and/or institution(s) as 'custom fields' on each case study content entry page. custom fields are not displayed by default - you can enable them by selecting the related check box after clicking on the "Screen Options" tab at the top-right of the case study content entry page.

a drawback of this setup is that it won't be easy in the future to e.g. list all the case studies contributed by person X or institution Y, but for the moment you can use the existing feature and if something more complex is useful later on, it will be easy to develop this.

please let me know if you can add authors with the current setup - i can help you tomorrow or Thursday if you are in the office.

**Comment by enorar** [comment]
@hotzeplotz It is working correctly. Thanks for the explanation.

**Comment by hotzeplotz** [comment]
that's great. please note that after installing the WordPress plugin needed to manage sidebars on pages, the list of pre-populated field names on the custom fields now shows many more possible field names, and limits the list to the first N (not sure how many) - you can still select Author as that's towards the beginning of the list, but for Institutions you need to click on the "Enter new" link just beneath the dropbox and manually insert 'Institution'.
