### ISSUE TITLE
Case study page description

### ISSUE THREAD

**Issue by enorar** [lsecities/urbangovernance-wp-theme#8]
Would it be possible to add a small box under to put some descriptive text about the case studies (same layout as on the "Explore the data" page)?

**Comment by hotzeplotz** [comment]
yes, i can add support for this.
you'll have to add any such text to a specific widget (under Appearance->Widgets in the WordPress dashboard) - i assume you would like to put here the blurb which is now posted as a case study with title "Contribute to the case studies"?

**Comment by hotzeplotz** [comment]
ok, this is now done and i used the initial text from the "Contribute the case studies" post, but if you need to change this, it's in Appearance->Widgets, then under "Posts home - header", within the Text widget in there.
