### ISSUE TITLE
case study sidebar updates

### ISSUE THREAD

**Issue by hotzeplotz** [lsecities/urbangovernance-wp-theme#9]
@enorar, i assume the sidebar on case study pages should have "Case study details" (rather than "Study case details"), and it would probably be best to hide the labels "Author/s" and "Institutions" whenever they don't have any content - can you confirm, please?

**Comment by enorar** [comment]
Yes that's correct! Thanks for your help Andrea

**Comment by hotzeplotz** [comment]
thanks, all done now :)
i also made a small change in that when there is only one author the label will be Author, when more than one it will be Authors - same for Institution(s).
and i indended a bit the lists (authors/institutions/categories) to more clearly split headings from their content, but if you think this doesn't work well please let me know and i will revert this change.
